static_thruster_allocation:
  thrusters:
    # Allocation matrix
    # For each thruster [ Fx, Fy, Fz, lx, ly, lz ] where F = forces and l = moments arms
    allocation_matrix: [0.707, -0.707,  0.0, -0.306, -0.062,  0.0,     
                        0.707,  0.707,  0.0, -0.306,  0.062,  0.0,     
                        0.000,  0.000, -1.0, -0.087, -0.120,  0.0,   
                        0.000,  0.000, -1.0, -0.087,  0.120,  0.0,        
                        0.707,  0.707,  0.0,  0.300, -0.197, -0.0,        
                        0.707, -0.707,  0.0,  0.300,  0.197, -0.0]  

    #Forces (N) = ct[0]*RPM^2 + c[1]*RPM + c[2]
    ctf: [0.00000177778, 0.0, 0.0]     # parameters for medusa seabotix, eqn -> Thrust = f(rpm)
    ctb: [-0.00000177778, 0.0, 0.0]     # parameters for medusa seabotix, eqn -> Thrust = f(rpm)
    #Maximum thrust each thruster is capable of outputting (N)
    max_thrust_norm:  36.0
    min_thrust_norm: -36.0
    # RPM max value /100
    actuators_gain: [45.0, 45.0, 45.0, 45.0, 45.0, 45.0]            # Inputs to actuators will be scaled to actuators_gain

inner_loops_pid:
    # minimum altitude safety
    min_alt: 2.0

    #timout for references [s]
    timout_ref: 0.5

    # bypass forces (hard - ignores inner-loop / soft - sums inner-loop and manual forces value)
    forces_hard_bypass: false

    # Yaw Params
    controllers:
        yaw:
            kp: 0.16
            ki: 0.0005
            kd: 0.133
            max_err:  60.0 # deg
            min_err: -60.0 # deg  
            max_out:  7.0 # N.m
            min_out: -7.0
        # Yaw Rate Params
        yaw_rate:
            kp: 0.16
            ki: 0.04444
            max_err:  3.0 # deg
            min_err: -3.0 # deg  
            max_out:  7.0 # N.m
            min_out: -7.0
        # Surge Params
        surge:
            kp: 26.0
            ki: 3.0
            max_ref:  0.7  # m/s
            min_ref: -0.7 # m/s
            max_err:  0.2 # m/s
            min_err: -0.2 # m/s  
            max_out:  15.0 # N
            min_out: -15.0
        # Sway Params
        sway:
            kp: 26.0
            ki: 3.0 
            max_ref:  0.5  # m/s
            min_ref: -0.5 # m/s
            max_err:  0.2 # m/s
            min_err: -0.2 # m/s  
            max_out:  25.0 # N
            min_out: -25.0
        # Depth Params
        depth:
            kp: 16
            ki: 1.6
            kd: 3.37
            max_err:  3.0 # m
            min_err: -3.0 # m  
            max_out:  20.0 # N
            min_out: -20.0
            min_alt: 1.0 # m
        # Altitude Params
        altitude:
            kp: 16
            ki: 1.6
            kd: 3.37
            max_err:  3.0 # m
            min_err: -3.0 # m  
            max_out:  20.0 # N
            min_out: -20.0 # N
            max_depth: 30.0 # m

waypoint:
    cdist: 1.5
    delta_t: 5.0
    type1:
      gains:
          ku: 1.0
          ks: 4.0
          speed_turn: 5.0
    type2:
      gains:
        k1: 0.05
        k2: 0.1
        k3: 0.1

# Path Following configurations
path_following:
  controller_gains:
    lapierre:
      k1: 1.0
      k2: 0.3
      k3: 0.3
      theta: 0.8
      k_delta: 1.0
    aguiar:
      delta: -1.0
      kx: 0.5
      ky: 0.5
      kz: 0.5
      k_pos: 0.5
      k_currents: 0.5
    romulo:
      ke: [0.05, 0.0, 0.0, 0.05]
      kz: 0.2
    pramod:
      kp: 0.01
      kd: 0.14
    samson:
      k1: 1.0
      k2: 0.3
      k3: 0.3
      theta: 0.8
      k_delta: 1.0