processes:
    - name: 'gazebo_simulation'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch experiments_bringup gazebo_simulation.launch'
      args:
            - x:= 0.0
            - y:= 0.0
            - z:= 0.0
            - roll:= 0.0
            - pitch:= 0.0
            - yaw:= 0.0
            - mode:= default
      dependencies:
            []
    - name: 'bags'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup bags.launch'
      args:
            - prefix:= sim
            - onebag:= true
      dependencies:
            []
    - name: 'tfs'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup simulation_tfs.launch'
      args:
            - broadcast_tf:= true
      dependencies:
            []
    - name: 'addons'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup addons.launch'
      args:
            - console_path_parser:= true
            - console_server:= true
      dependencies:
            []
    - name: 'navigation'
      launch_on_startup: true
      delay_before_start: 4.0
      cmd: 'roslaunch medusa_bringup nav.launch'
      args:
            - filter:= true
            - gnss2utm:= true
            - auvstate2mstate:= true
      dependencies:
            []
    - name: 'controllers'
      launch_on_startup: true
      delay_before_start: 5.0
      cmd: 'roslaunch medusa_bringup controls.launch'
      args:
            - static_thruster_allocation:= true
            - inner_loops_pid:= true
            - waypoint:= true
            - path_following:= true
      dependencies:
            []
    - name: 'planning'
      launch_on_startup: true
      delay_before_start: 5.0
      cmd: 'roslaunch medusa_bringup planning.launch'
      args:
            - dsor_paths:= true
      dependencies:
            []