## --------------------------- ## 
#  medusa_addons                #
## --------------------------- ## 
addons/console_path_parser:
    node_frequency: 5
    topics:
        subscribers: 
            Mission_String: /myellow/addons/Mission_String
            state: /myellow/nav/filter/state
            flag: /myellow/Flag
        publishers:
            Path_Section: /myellow/addons/path_section
            Formation: /myellow/addons/formation
            biased_formation: /myellow/addons/biased_formation
            WPRef: /myellow/addons/WPRef
            DepthRef: /myellow/ref/depth
            AltRef: /myellow/ref/altitude
            FullMission: /myellow/addons/full_mission
        services:
            reset_path: "/myellow/ResetPath"
            arc2d_path: "/myellow/SpawnArc2DPath"
            line_path: "/myellow/SpawnLinePath"
            pf_start: "/myellow/PFStart"
            pf_stop: "/myellow/PFStop"
            set_speed: "/myellow/SetConstVdVehicle"

addons/console_server:
    topics:
      services:
          wp_standard: "/myellow/controls/send_wp_standard"
          wp_loose: "/myellow/controls/send_wp_loose"
          wp_heading: "/myellow/controls/send_wp_heading"
      console:
          waypoint: "wp_standard"

## --------------------------- ## 
#  medusa_nav                   #
## --------------------------- ## 
### Sensor myellow for the frame "odom"
nav/filter:
    node_frequency: 10      # ROS node rate
    topics:
        # reset, position topic, velocity topic and orientation and acceleration (optional) topic
        subscribers: ["/myellow/nav/reset", "/myellow/measurement/position", "/myellow/measurement/velocity", "/myellow/measurement/orientation"]
        # state topic, debug topic
        publishers: ["/myellow/nav/filter/state", "/myellow/nav/filter/debug"]     
    topics_dr:
       velocity: "/myellow/measurement/velocity"
       orientation: "/myellow/measurement/orientation"
       true_state: "/myellow/nav/filter/state"
       flag: "/myellow/Flag"
       dead_reckoning: "/myellow/nav/filter/state_dr"
       dead_reckoning_console: "/myellow/State_dr"
    services_dr:
       reset_filter_dr: "/myellow/nav/reset_filter_dr"

### Converting sensor_msgs::NavSatFix to medusa_msgs::Measurement data type
nav/gnss2utm:
    node_frequency: 10
    topics:
        subscribers: [ "/myellow/sensors/gnss" ]
        publishers: [ "/myellow/measurement/position" ]
        ground_truth: "/myellow/State_gt"
    services:
        enable_gps: "/myellow/sensor/enable_gps"

nav/auvstate2mstate:
    node_frequency: 10
    topics:
        subscribers: [ "/myellow/nav/filter/state", "/myellow/drivers/inside_pressure/data", "/myellow/sensors/gnss" ]
        publishers:  [ "/myellow/State" ]

## --------------------------- ## 
#  medusa_control               #
## --------------------------- ## 

### Static Thruster Allocation
controls/static_thruster_allocation:
    topics:
        subscribers:
            thrust_body_request: "/myellow/thrust_body_request"
        publishers:
            thrusters: "/myellow/thrusters/rpm_command"

### Inner Loops PID
controls/inner_loops_pid:
    # ROS node rate 
    node_frequency: 10.0 # Time parameters
    # ROS Topics
    topics:
        subscribers:
            yaw: "/myellow/ref/yaw"
            pitch: "/myellow/ref/pitch"
            roll: "/myellow/ref/roll"
            yaw_rate: "/myellow/ref/yaw_rate"
            pich_rate: "/myellow/ref/pitch_rate"
            roll_rate: "/myellow/ref/roll_rate"
            surge: "/myellow/ref/surge"
            sway: "/myellow/ref/sway"
            heave: "/myellow/ref/heave"
            depth: "/myellow/ref/depth"
            altitude: "/myellow/ref/altitude"
            altitude_safety: "/myellow/ref/altitude_safety"
            depth_safety: "/myellow/ref/depth_safety"
            state: "/myellow/nav/filter/state"
        publishers:
            thrust_body_request: "/myellow/thrust_body_request"

### Way Point
controls/waypoint:
    node_frequency: 10.0
    topics:
        publishers:
            yaw_ref: "/myellow/ref/yaw"
            yaw_rate_ref: "/myellow/ref/yaw_rate"
            u_ref: "/myellow/ref/surge"
            v_ref: "/myellow/ref/sway"
            flag: "/myellow/Flag"
        subscribers:
            flag: "/myellow/Flag"
            state: "/myellow/nav/filter/state"
        services:
            wp_standard: "/myellow/controls/send_wp_standard"
            wp_loose: "/myellow/controls/send_wp_loose"
            wp_heading: "/myellow/controls/send_wp_heading"


### Path Following
controls/path_following:
    node_frequency: 10.0
    flag: "/myellow/Flag"
    topics:
        subscribers:
            state: "/myellow/nav/filter/state"
            path: "/myellow/PathData"
            vc: "/myellow/PF/vc"
        publishers:
            # Publishers for linear motion
            surge: "/myellow/ref/surge"
            sway: "/myellow/ref/sway"
            heave: "/myellow/ref/heave"
    
            # Publishers for angular motion
            roll: "/myellow/ref/roll"
            roll_rate: "/myellow/ref/roll_rate"
            pitch: "/myellow/ref/pitch"
            pitch_rate: "/myellow/ref/pitch_rate"
            yaw: "/myellow/ref/yaw"
            yaw_rate: "/myellow/ref/yaw_rate"
    
            # Publishers for the virtual target
            rabbit: "/myellow/Gamma"
            
            # Observer for the currents
            observer:
                x: "/myellow/current/x"
                y: "/myellow/current/y"

            # Publish info for plots
            pfollowing_debug: "myellow/pfollowing/debug"
        # Define here the service names to switch between controllers 
        services:
            # Service names to start and stop the path following algorithm
            start_pf: "/myellow/PFStart"
            stop_pf: "/myellow/PFStop"
            updates_gains_pf: "/myellow/PFUpdateGains"
            reset_vt_pf: "/myellow/ResetVT"
    
            # Service names to switch the path following algorithm
            marcelo_pf: "/myellow/PFSetMarcelo"
            aguiar_pf: "/myellow/PFSetAguiar"
            brevik_pf: "/myellow/PFSetBrevik"
            fossen_pf: "/myellow/PFSetFossen"
            romulo_pf: "/myellow/PFSetRomulo"
            lapierre_pf: "/myellow/PFSetLapierre"
            pramod_pf: "/myellow/PFSetPramod"
            samson_pf: "/myellow/PFSetSamson"
            # Service names related to the path
            reset_path: "/myellow/ResetPath"
            set_path_mode: "/myellow/SetMode"
            # Service names related to the waypoint
            wp_standard: "/myellow/controls/send_wp_standard"

## --------------------------- ## 
#  medusa_planning              #
## --------------------------- ##
planning/dsor_paths:
    node_frequency: 10.0
    frame_id: "Path_frame"
    topics:
        subscribers:
            gamma: "/myellow/Gamma"
            vehicle_state: "/myellow/nav/filter/state"
        publishers:
            path_data: "/myellow/PathData"
            virtual_target_state: "/myellow/Virtual/State"
        # Services for constructing a path
        services:
            reset_path: "/myellow/ResetPath"
            set_mode: "/myellow/SetMode"
            arc2d_path: "/myellow/SpawnArc2DPath"
            bernoulli_path: "/myellow/SpawnBernoulliPath"
            circle2d_path: "/myellow/SpawnCircle2DPath"
            line_path: "/myellow/SpawnLinePath"
            speed:
                const_rabbit_speed: "/myellow/SetConstVdRabbit"
                const_vehicle_speed: "/myellow/SetConstVdVehicle"
